anguage: elixir

elixir:
  - 1.4.1

addons:
  postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix ecto.create, ecto.migrate

script:
  - mix test